import Head from 'next/head'
import Image from 'next/image'
import Login from '../Components/Login'
import styles from '../styles/Home.module.css'
import { useMoralis } from 'react-moralis'

export default function Home() {
  const {isAuthenticated,logout}=useMoralis();


  if(!isAuthenticated) return <Login/>;
  return (
    <div className='h-screen'>
      <Head>
        <title>Harshajop's Magicverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to App</h1>
      <button onClick={logout}>LogOut</button>
    </div>
  )
}
