import Head from 'next/head'
import Image from 'next/image'
import Login from '../Components/Login'
import { useMoralis } from 'react-moralis'
import Header from '../Components/Header';
import Messages from '../Components/Messages';

export default function Home() {
  const {isAuthenticated,logout}=useMoralis();


  if(!isAuthenticated) return <Login/>;
  return (
    <div className='h-screen overflow-y-scroll bg-gradient-to-b from-black to-purple-900 overflow-hidden'>
      <Head>
        <title>Harshajop Magicverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='max-w-screen-2xl mx-auto'>
          <Header></Header>
          <Messages></Messages>
        </div>
    </div>
  )
}
